name: run-pytest

on:
  workflow_dispatch: 
  push:
    branches: [main]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
  pull_request:

jobs:
  pytest:
    runs-on: [ubuntu-latest]
    steps: 

      - name: downgrade-python
        shell: bash
        run: |
          deactivate
          sudo apt-get purge python3.10
          sudo apt-get autoremove
          sudo apt-get update
          sudo apt-get install python3.8

      - name: checkout-code
        uses: actions/checkout@v4

      - name: install-poetry
        shell: bash
        run : |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          echo $(poetry --version)
          echo $(python --version)

      - name: config-poetry
        shell: bash
        run: |
          poetry config virtualenvs.in-project true
          poetry config installer.modern-installation false
          pip install numpy==1.19.5

      - name: install-poetry-venv
        shell: bash
        run: |
          poetry install
      
      - name: run-pytest
        shell: bash 
        run: poetry run pytest -vv