artists = [
    "Phish",
    "Red Hot Chili Peppers",
    "Muse",
    "Blink-182",
    "Depeche Mode",
    "Elton John",
    "Coldplay",
    "Sting",
    "James Taylor",
    "John Fogerty",
    "Blue Oyster Cult",
    "Deep Purple",
    "Bob Dylan",
    "The Eagles",
    "The Rolling Stones",
    "Rick Springfield",
    "John Mellencamp",
    "Nick Lowe",
    "The Who",
    "Aerosmith",
    "Bon Jovi",
    "Green Day",
    "KISS",
    "Metallica",
    "Pearl Jam",
    "Rage Against the Machine",
    "Soundgarden",
    "U2",
    "The Police",
    "The Clash",
    "Pink Floyd",
    "Queen",
    "Led Zeppelin",
    "The Beatles",
    "Rolling Stones",
    "The Smiths",
    "The Jam",
    "The Cure",
    "Depeche Mode",
    "New Order",
    "Joy Division",
    "The Stone Roses",
    "Oasis",
    "Blur",
    "Radiohead",
    "Arctic Monkeys",
    "Coldplay",
    "Muse",
    "Red Hot Chili Peppers",
    "Phish",
    "The Rolling Stones",
    "The Eagles",
    "The Who",
    "Pink Floyd",
    "Queen",
    "Led Zeppelin",
    "The Beatles",
    "Rolling Stones",
    "The Smiths",
    "The Jam",
    "The Cure",
    "Depeche Mode",
    "New Order",
    "Joy Division",
    "The Stone Roses",
    "Oasis",
    "Blur",
    "Radiohead",
    "Arctic Monkeys",
    "Coldplay",
    "Muse",
    "Red Hot Chili Peppers",
    "Phish",
    "The Rolling Stones",
    "The Eagles",
    "The Who",
    "Pink Floyd",
    "Queen",
    "Led Zeppelin",
    "The Beatles",
    "Rolling Stones",
    "The Smiths",
    "The Jam",
    "The Cure",
    "Depeche Mode",
    "New Order",
    "Joy Division",
    "The Stone Roses",
    "Oasis",
    "Blur",
    "Radiohead",
    "Arctic Monkeys",
    "Coldplay",
    "Muse",
    "Red Hot Chili Peppers",
    "Phish",
    "The Rolling Stones",
    "The Eagles",
    "The Who",
    "Pink Floyd",
    "Queen",
    "Led Zeppelin",
    "The Beatles",
    "Rolling Stones",
]
